"""
Regime-Based Trading Bot for Interactive Brokers
==================================================

Classifies market regime (TRENDING, RANGING, VOLATILE) using ADX, ATR,
and EMA analysis, then routes to appropriate strategy logic:
- TRENDING → EMA pullback entries with trailing stops
- RANGING → RSI extreme entries with BB-based exits
- VOLATILE → no new entries, tighten existing stops

Uses RiskManager for position sizing and cooldown, OrderManager for
bracket order execution, and AlertDispatcher for notifications.

Usage:
    trader = RegimeTrader(connection, order_manager, fetcher, notifier=dispatcher)
    trader.run("AAPL", interval_seconds=300)
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


class MarketRegime(Enum):
    TRENDING = "TRENDING"
    RANGING = "RANGING"
    VOLATILE = "VOLATILE"
    UNKNOWN = "UNKNOWN"


@dataclass
class RegimeConfig:
    """Configuration for the regime trader."""

    # Regime detection
    adx_length: int = 14
    adx_trend_threshold: float = 25.0
    adx_range_threshold: float = 20.0
    atr_length: int = 14
    atr_volatility_mult: float = 1.5
    atr_avg_length: int = 50

    # Trend strategy (EMA pullback)
    ema_fast: int = 9
    ema_slow: int = 21
    ema_trend_filter: int = 200
    trend_atr_stop_mult: float = 2.0
    trend_rr_ratio: float = 2.0

    # Mean reversion strategy (RSI + BB)
    bb_length: int = 20
    bb_deviation: float = 2.0
    rsi_length: int = 14
    rsi_overbought: float = 70.0
    rsi_oversold: float = 30.0

    # Data
    bar_duration: str = "30 D"
    bar_size: str = "5 mins"

    # Execution
    position_size_pct: float = 2.0
    capital: float = 100000.0


@dataclass
class RegimeSignal:
    """Signal generated by the regime trader."""
    timestamp: datetime
    symbol: str
    regime: MarketRegime
    action: str  # "BUY", "SELL", "HOLD"
    entry_price: float = 0.0
    stop_price: float = 0.0
    target_price: float = 0.0
    reason: str = ""


class RegimeTrader:
    """Regime-based trading bot using IB data and execution.

    Args:
        connection: An IBInsyncConnection instance.
        order_manager: OrderManager for trade execution.
        fetcher: HistoricalDataFetcher for bar data.
        risk_manager: Optional RiskManager for sizing/cooldown.
        notifier: Optional AlertDispatcher for notifications.
        config: RegimeConfig with strategy parameters.
        ml_classifier: Optional MLRegimeClassifier for ML-based regime detection.
    """

    def __init__(
        self,
        connection: Any,
        order_manager: Any,
        fetcher: Any,
        risk_manager: Any = None,
        notifier: Any = None,
        config: Optional[RegimeConfig] = None,
        ml_classifier: Any = None,
    ) -> None:
        self.connection = connection
        self.order_manager = order_manager
        self.fetcher = fetcher
        self.risk_manager = risk_manager
        self.notifier = notifier
        self.config = config or RegimeConfig()
        self.ml_classifier = ml_classifier  # Optional MLRegimeClassifier

        self._current_regime = MarketRegime.UNKNOWN
        self._position: Optional[str] = None  # "LONG", "SHORT", or None
        self._entry_price: float = 0.0
        self._signal_history: List[RegimeSignal] = []
        self._running = False

    # ─── Technical Indicators ───

    @staticmethod
    def _calculate_adx(df: pd.DataFrame, length: int = 14) -> pd.Series:
        """Calculate ADX from OHLC data."""
        high = df["high"]
        low = df["low"]
        close = df["close"]

        plus_dm = high.diff()
        minus_dm = -low.diff()
        plus_dm = plus_dm.where((plus_dm > minus_dm) & (plus_dm > 0), 0.0)
        minus_dm = minus_dm.where((minus_dm > plus_dm) & (minus_dm > 0), 0.0)

        tr1 = high - low
        tr2 = (high - close.shift(1)).abs()
        tr3 = (low - close.shift(1)).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

        atr = tr.ewm(alpha=1.0 / length, min_periods=length).mean()
        plus_di = 100 * (plus_dm.ewm(alpha=1.0 / length, min_periods=length).mean() / atr)
        minus_di = 100 * (minus_dm.ewm(alpha=1.0 / length, min_periods=length).mean() / atr)

        dx = 100 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, np.nan)
        adx = dx.ewm(alpha=1.0 / length, min_periods=length).mean()
        adx = adx.fillna(0)

        return adx

    @staticmethod
    def _calculate_atr(df: pd.DataFrame, length: int = 14) -> pd.Series:
        """Calculate Average True Range."""
        high = df["high"]
        low = df["low"]
        close = df["close"]

        tr1 = high - low
        tr2 = (high - close.shift(1)).abs()
        tr3 = (low - close.shift(1)).abs()
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

        return tr.ewm(alpha=1.0 / length, min_periods=length).mean()

    @staticmethod
    def _calculate_rsi(series: pd.Series, length: int = 14) -> pd.Series:
        """Calculate RSI."""
        delta = series.diff()
        gain = delta.where(delta > 0, 0.0)
        loss = -delta.where(delta < 0, 0.0)

        avg_gain = gain.ewm(alpha=1.0 / length, min_periods=length).mean()
        avg_loss = loss.ewm(alpha=1.0 / length, min_periods=length).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        return 100 - (100 / (1 + rs))

    @staticmethod
    def _calculate_bollinger(
        series: pd.Series, length: int = 20, deviation: float = 2.0
    ) -> tuple[pd.Series, pd.Series, pd.Series]:
        """Calculate Bollinger Bands. Returns (upper, mid, lower)."""
        mid = series.rolling(window=length).mean()
        std = series.rolling(window=length).std()
        upper = mid + std * deviation
        lower = mid - std * deviation
        return upper, mid, lower

    # ─── Regime Detection ───

    def detect_regime(self, df: pd.DataFrame) -> MarketRegime:
        """Classify current market regime.

        Uses ML classifier if available, otherwise falls back to
        ADX/ATR-based heuristic detection.

        Args:
            df: OHLCV DataFrame with recent bars.

        Returns:
            MarketRegime enum value.
        """
        # ML-based detection (if available)
        if self.ml_classifier is not None:
            try:
                ml_regime = self.ml_classifier.predict(df)
                proba = self.ml_classifier.predict_proba(df)
                confidence = max(proba.values()) if proba else 0.0

                # Map ML regime to local MarketRegime enum
                regime_map = {
                    "TRENDING": MarketRegime.TRENDING,
                    "RANGING": MarketRegime.RANGING,
                    "VOLATILE": MarketRegime.VOLATILE,
                }
                ml_regime_name = ml_regime if isinstance(ml_regime, str) else ml_regime.name
                regime = regime_map.get(ml_regime_name, MarketRegime.UNKNOWN)

                if regime != self._current_regime:
                    logger.info(
                        "ML Regime change: %s → %s (confidence=%.2f, proba=%s)",
                        self._current_regime.value,
                        regime.value,
                        confidence,
                        proba,
                    )
                    self._current_regime = regime

                return regime

            except Exception as e:
                logger.warning(
                    "ML regime detection failed, falling back to ADX: %s", e
                )

        # ADX/ATR-based fallback
        cfg = self.config

        adx = self._calculate_adx(df, cfg.adx_length)
        atr = self._calculate_atr(df, cfg.atr_length)
        atr_avg = atr.rolling(window=cfg.atr_avg_length).mean()

        current_adx = adx.iloc[-1]
        current_atr = atr.iloc[-1]
        current_atr_avg = atr_avg.iloc[-1]

        is_volatile = current_atr > current_atr_avg * cfg.atr_volatility_mult

        if is_volatile:
            regime = MarketRegime.VOLATILE
        elif current_adx > cfg.adx_trend_threshold:
            regime = MarketRegime.TRENDING
        elif current_adx < cfg.adx_range_threshold:
            regime = MarketRegime.RANGING
        else:
            regime = MarketRegime.UNKNOWN

        if regime != self._current_regime:
            logger.info(
                "Regime change: %s → %s (ADX=%.1f, ATR=%.2f, ATR_avg=%.2f)",
                self._current_regime.value,
                regime.value,
                current_adx,
                current_atr,
                current_atr_avg,
            )
            self._current_regime = regime

        return regime

    # ─── Signal Generation ───

    def generate_signal(
        self, symbol: str, df: pd.DataFrame
    ) -> RegimeSignal:
        """Generate a trading signal based on current regime.

        Args:
            symbol: Ticker symbol.
            df: OHLCV DataFrame.

        Returns:
            RegimeSignal with action and levels.
        """
        regime = self.detect_regime(df)
        cfg = self.config
        close = df["close"]
        current_price = close.iloc[-1]

        atr = self._calculate_atr(df, cfg.atr_length)
        current_atr = atr.iloc[-1]

        action = "HOLD"
        stop_price = 0.0
        target_price = 0.0
        reason = f"Regime: {regime.value}"

        if regime == MarketRegime.TRENDING:
            action, stop_price, target_price, reason = self._trend_signal(
                df, current_price, current_atr
            )
        elif regime == MarketRegime.RANGING:
            action, stop_price, target_price, reason = self._range_signal(
                df, current_price, current_atr
            )
        elif regime == MarketRegime.VOLATILE:
            reason = "VOLATILE — no new entries"

        signal = RegimeSignal(
            timestamp=datetime.now(),
            symbol=symbol,
            regime=regime,
            action=action,
            entry_price=current_price if action != "HOLD" else 0.0,
            stop_price=stop_price,
            target_price=target_price,
            reason=reason,
        )

        self._signal_history.append(signal)
        logger.info(
            "Signal: %s %s @ $%.2f | Stop=$%.2f | Target=$%.2f | %s",
            action,
            symbol,
            current_price,
            stop_price,
            target_price,
            reason,
        )

        return signal

    def _trend_signal(
        self,
        df: pd.DataFrame,
        price: float,
        atr: float,
    ) -> tuple[str, float, float, str]:
        """Generate trend-following signal (EMA pullback)."""
        cfg = self.config
        close = df["close"]

        ema_fast = close.ewm(span=cfg.ema_fast, adjust=False).mean()
        ema_slow = close.ewm(span=cfg.ema_slow, adjust=False).mean()
        ema_200 = close.ewm(span=cfg.ema_trend_filter, adjust=False).mean()

        above_200 = price > ema_200.iloc[-1]
        below_200 = price < ema_200.iloc[-1]

        # Pullback to fast EMA in uptrend
        pullback_long = (
            above_200
            and ema_fast.iloc[-1] > ema_slow.iloc[-1]
            and df["low"].iloc[-1] <= ema_fast.iloc[-1]
            and price > ema_fast.iloc[-1]
        )

        # Pullback to fast EMA in downtrend
        pullback_short = (
            below_200
            and ema_fast.iloc[-1] < ema_slow.iloc[-1]
            and df["high"].iloc[-1] >= ema_fast.iloc[-1]
            and price < ema_fast.iloc[-1]
        )

        if pullback_long and self._position is None:
            stop = price - atr * cfg.trend_atr_stop_mult
            risk = price - stop
            target = price + risk * cfg.trend_rr_ratio
            return "BUY", stop, target, "Trend pullback to EMA (long)"

        if pullback_short and self._position is None:
            stop = price + atr * cfg.trend_atr_stop_mult
            risk = stop - price
            target = price - risk * cfg.trend_rr_ratio
            return "SELL", stop, target, "Trend pullback to EMA (short)"

        return "HOLD", 0.0, 0.0, "Trending — waiting for pullback"

    def _range_signal(
        self,
        df: pd.DataFrame,
        price: float,
        atr: float,
    ) -> tuple[str, float, float, str]:
        """Generate mean-reversion signal (RSI + BB)."""
        cfg = self.config
        close = df["close"]

        rsi = self._calculate_rsi(close, cfg.rsi_length)
        bb_upper, bb_mid, bb_lower = self._calculate_bollinger(
            close, cfg.bb_length, cfg.bb_deviation
        )

        current_rsi = rsi.iloc[-1]
        current_bb_mid = bb_mid.iloc[-1]

        if current_rsi < cfg.rsi_oversold and price <= bb_lower.iloc[-1] and self._position is None:
            stop = price - atr * 1.5
            target = current_bb_mid
            return "BUY", stop, target, f"MR Long: RSI={current_rsi:.1f} at BB lower"

        if current_rsi > cfg.rsi_overbought and price >= bb_upper.iloc[-1] and self._position is None:
            stop = price + atr * 1.5
            target = current_bb_mid
            return "SELL", stop, target, f"MR Short: RSI={current_rsi:.1f} at BB upper"

        return "HOLD", 0.0, 0.0, f"Ranging — RSI={current_rsi:.1f}, waiting for extremes"

    # ─── Execution ───

    def execute_signal(self, signal: RegimeSignal) -> Optional[Any]:
        """Execute a trading signal via OrderManager.

        Args:
            signal: The RegimeSignal to execute.

        Returns:
            List of Trade objects from bracket order, or None.
        """
        if signal.action == "HOLD":
            return None

        # Check risk manager
        if self.risk_manager and not self.risk_manager.can_trade():
            logger.warning("RiskManager blocked trade: %s %s", signal.action, signal.symbol)
            return None

        # Calculate position size
        if self.risk_manager:
            qty = self.risk_manager.calculate_position_size(
                signal.symbol, signal.entry_price, signal.stop_price
            )
        else:
            risk_amount = self.config.capital * (self.config.position_size_pct / 100.0)
            risk_per_share = abs(signal.entry_price - signal.stop_price)
            qty = max(1, int(risk_amount / risk_per_share)) if risk_per_share > 0 else 1

        try:
            action = "BUY" if signal.action == "BUY" else "SELL"
            trades = self.order_manager.bracket_order(
                symbol=signal.symbol,
                action=action,
                quantity=qty,
                limit_price=signal.entry_price,
                take_profit=signal.target_price,
                stop_loss=signal.stop_price,
            )

            self._position = "LONG" if action == "BUY" else "SHORT"
            self._entry_price = signal.entry_price

            if self.risk_manager:
                risk_amount = abs(signal.entry_price - signal.stop_price) * qty
                self.risk_manager.add_position(signal.symbol, risk_amount)

            msg = (
                f"Regime Trade: {action} {qty} {signal.symbol} @ ${signal.entry_price:.2f} "
                f"| SL=${signal.stop_price:.2f} TP=${signal.target_price:.2f} "
                f"| Regime: {signal.regime.value} | {signal.reason}"
            )
            logger.info(msg)
            if self.notifier:
                self.notifier.dispatch("Regime Trade", msg)

            return trades

        except Exception as e:
            logger.error("Failed to execute signal: %s", e)
            if self.notifier:
                self.notifier.dispatch(
                    "Trade Error",
                    f"Failed to execute {signal.action} {signal.symbol}: {e}",
                    priority="CRITICAL",
                )
            return None

    # ─── Main Loop ───

    def run(
        self,
        symbol: str,
        interval_seconds: int = 300,
        max_iterations: Optional[int] = None,
    ) -> None:
        """Main trading loop.

        Args:
            symbol: Ticker symbol to trade.
            interval_seconds: Seconds between iterations.
            max_iterations: Stop after N iterations (None = run forever).
        """
        self._running = True
        iteration = 0

        logger.info(
            "RegimeTrader started: %s | interval=%ds | config=%s",
            symbol,
            interval_seconds,
            self.config,
        )

        try:
            while self._running:
                if max_iterations and iteration >= max_iterations:
                    logger.info("Max iterations reached (%d). Stopping.", max_iterations)
                    break

                try:
                    df = self.fetcher.fetch_bars(
                        symbol,
                        duration=self.config.bar_duration,
                        bar_size=self.config.bar_size,
                    )

                    if df.empty:
                        logger.warning("No data for %s. Retrying...", symbol)
                        time.sleep(interval_seconds)
                        continue

                    signal = self.generate_signal(symbol, df)
                    if signal.action != "HOLD":
                        self.execute_signal(signal)

                except Exception as e:
                    logger.error("Error in trading loop: %s", e)

                iteration += 1
                time.sleep(interval_seconds)

        except KeyboardInterrupt:
            logger.info("RegimeTrader stopped by user.")
        finally:
            self._running = False

    def stop(self) -> None:
        """Signal the trading loop to stop."""
        self._running = False
        logger.info("RegimeTrader stop requested.")

    def get_signal_history(self) -> List[RegimeSignal]:
        """Return all generated signals."""
        return list(self._signal_history)
